### ISSUE TITLE
Update readme.md file

### ISSUE THREAD

**Issue by Rajeet10** [Rajeet10/Teenflix#1]
Add a new readme file to cover all aspect of project

**Comment by arushi-mittal** [comment]
Hi, I would like to work on this issue. Please assign it to me.

**Comment by Rajeet10** [comment]
> Hi, I would like to work on this issue. Please assign it to me.

Ya sure go ahead

**Comment by arushi-mittal** [comment]
Hi, please review my PR for this issue. Thanks!

**Comment by Rajeet10** [comment]
@arushi-mittal Yeah done! Great work Thanks again for the documentation. I really like it .It is awesome
